# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
import initialise as i

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
i.hint(2)

hint: np.__version__, np.show_config)


In [4]:
np.__version__

'1.17.4'

In [5]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
a = np.zeros(10, dtype=int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
i.hint(4)

hint: size, itemsize


In [8]:
f'size: This attribute gives the number of elements present in the NumPy array: {a.size}, itemsize: This attribute gives the memory size of one element of NumPy array in bytes: {a.itemsize}'

'size: This attribute gives the number of elements present in the NumPy array: 10, itemsize: This attribute gives the memory size of one element of NumPy array in bytes: 8'

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [9]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x7fb1ca0f19e8>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [11]:
i.hint(6)

hint: array[4]


Checked solution, and got the same answer

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [13]:
i.hint(8)

hint: array[::-1]


In [14]:
b[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
i.hint(9)

hint: reshape


In [16]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [17]:
c=np.array([1,2,0,0,4,0])
c=c[c!=0]


In [18]:
np.indices((0,3))

array([], shape=(2, 0, 3), dtype=int64)

In [19]:
print(np.indices((0,3)))

[]


In [20]:
np.indices((1,3)).shape

(2, 1, 3)

In [21]:
i.hint(10)

hint: np.nonzero


In [22]:
c=np.array([1,2,0,0,4,0])
c

array([1, 2, 0, 0, 4, 0])

In [23]:
d =np.nonzero(c)
d, type(d)

((array([0, 1, 4]),), tuple)

In [24]:
d[0]

array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [25]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [26]:
np.random.randn(3,3,3)

array([[[ 1.40801018,  1.36456001, -0.27258459],
        [ 0.27985113,  1.7904729 , -0.86373835],
        [-0.41048245,  0.31052372,  0.95949479]],

       [[ 0.33718162,  0.09807095, -0.09228761],
        [-0.12312755, -1.46220109,  0.7043073 ],
        [-1.07365986,  0.50933849, -1.30982891]],

       [[ 0.59247258, -0.69584502,  0.1658766 ],
        [-0.38370831,  1.13305873,  1.47788805],
        [-1.64774572,  0.63573038, -1.73920343]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [27]:
a = np.random.randn(10, 10)

In [28]:
a.min()

-2.2197113988427457

In [29]:
a.max()

2.7958143877812596

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [30]:
a=np.random.randn(30)
a

array([-0.28591651, -0.50279558, -0.28283973, -1.48742923,  1.53321441,
       -2.49974194,  2.60320684, -0.71002455, -1.08671686,  0.33632741,
       -0.51872072,  2.07188985,  1.05592071,  0.52917018, -0.34468524,
        0.49855516,  0.46343311,  0.73018536, -0.13385135,  1.34519624,
       -0.58158883,  0.11384269, -1.35505926,  0.26886482, -2.00621381,
       -1.45357523, -0.13981108, -0.16825367,  0.64097183,  0.97374613])

In [31]:
a.mean()

-0.013089962313792121

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [32]:
i.hint(15)

hint: array[1:-1, 1:-1]


In [33]:
a = np.ones((10,10))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [34]:
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
a[1:-1,1:-1]

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [38]:
a = np.random.randint(1,100,size=(10,10))
a

array([[ 3, 42, 91, 45, 75, 82, 34, 95, 22, 15],
       [57, 57, 47, 78, 72, 32, 55, 50,  4, 62],
       [64, 80, 50, 77, 77, 70, 40,  8, 24, 66],
       [45,  7, 83, 93, 77, 86, 26, 92, 62,  6],
       [ 7, 42, 42, 44, 24, 27, 25, 38, 63, 32],
       [17, 35, 89, 99, 75, 81, 15, 57, 35, 81],
       [99, 98, 91, 88, 26, 91, 57, 86, 88, 65],
       [17, 89, 51,  8, 17, 18, 20, 67, 46, 22],
       [81, 89, 69,  5,  2, 62, 27, 83, 98, 82],
       [76, 58, 89, 79, 60, 81, 43, 30, 76, 10]])

In [39]:
a[:,0]=0
a

array([[ 0, 42, 91, 45, 75, 82, 34, 95, 22, 15],
       [ 0, 57, 47, 78, 72, 32, 55, 50,  4, 62],
       [ 0, 80, 50, 77, 77, 70, 40,  8, 24, 66],
       [ 0,  7, 83, 93, 77, 86, 26, 92, 62,  6],
       [ 0, 42, 42, 44, 24, 27, 25, 38, 63, 32],
       [ 0, 35, 89, 99, 75, 81, 15, 57, 35, 81],
       [ 0, 98, 91, 88, 26, 91, 57, 86, 88, 65],
       [ 0, 89, 51,  8, 17, 18, 20, 67, 46, 22],
       [ 0, 89, 69,  5,  2, 62, 27, 83, 98, 82],
       [ 0, 58, 89, 79, 60, 81, 43, 30, 76, 10]])

In [40]:
a[:,-1]=0
a

array([[ 0, 42, 91, 45, 75, 82, 34, 95, 22,  0],
       [ 0, 57, 47, 78, 72, 32, 55, 50,  4,  0],
       [ 0, 80, 50, 77, 77, 70, 40,  8, 24,  0],
       [ 0,  7, 83, 93, 77, 86, 26, 92, 62,  0],
       [ 0, 42, 42, 44, 24, 27, 25, 38, 63,  0],
       [ 0, 35, 89, 99, 75, 81, 15, 57, 35,  0],
       [ 0, 98, 91, 88, 26, 91, 57, 86, 88,  0],
       [ 0, 89, 51,  8, 17, 18, 20, 67, 46,  0],
       [ 0, 89, 69,  5,  2, 62, 27, 83, 98,  0],
       [ 0, 58, 89, 79, 60, 81, 43, 30, 76,  0]])

In [41]:
a[0]=0
a

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 57, 47, 78, 72, 32, 55, 50,  4,  0],
       [ 0, 80, 50, 77, 77, 70, 40,  8, 24,  0],
       [ 0,  7, 83, 93, 77, 86, 26, 92, 62,  0],
       [ 0, 42, 42, 44, 24, 27, 25, 38, 63,  0],
       [ 0, 35, 89, 99, 75, 81, 15, 57, 35,  0],
       [ 0, 98, 91, 88, 26, 91, 57, 86, 88,  0],
       [ 0, 89, 51,  8, 17, 18, 20, 67, 46,  0],
       [ 0, 89, 69,  5,  2, 62, 27, 83, 98,  0],
       [ 0, 58, 89, 79, 60, 81, 43, 30, 76,  0]])

In [42]:
a[-1]=0
a

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 57, 47, 78, 72, 32, 55, 50,  4,  0],
       [ 0, 80, 50, 77, 77, 70, 40,  8, 24,  0],
       [ 0,  7, 83, 93, 77, 86, 26, 92, 62,  0],
       [ 0, 42, 42, 44, 24, 27, 25, 38, 63,  0],
       [ 0, 35, 89, 99, 75, 81, 15, 57, 35,  0],
       [ 0, 98, 91, 88, 26, 91, 57, 86, 88,  0],
       [ 0, 89, 51,  8, 17, 18, 20, 67, 46,  0],
       [ 0, 89, 69,  5,  2, 62, 27, 83, 98,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [43]:
a=np.random.randint(1,100, size=(10,10))
a

array([[82, 43,  3,  6, 43, 55, 31, 24,  2, 33],
       [82, 10, 81, 44,  5, 18, 63, 31, 60, 26],
       [ 1, 98, 16, 42,  8, 53, 49,  1, 37, 21],
       [41, 65, 96, 93,  7, 13, 22, 75, 63, 52],
       [19,  7, 62, 34, 63, 43, 51, 52, 52, 25],
       [61, 73, 90, 78, 72, 83, 23, 59, 43, 58],
       [85, 51, 86, 74, 39, 59, 63, 29, 25,  2],
       [ 1, 20, 97, 66, 44, 56, 64, 36, 83, 52],
       [89, 99, 87, 90, 15, 89, 26, 83, 56, 59],
       [55, 69, 61, 32, 93, 36, 27, 73, 70, 26]])

In [44]:
#calling specific columns array[:,[column1,column2]]
a[:,[0,-1]]

array([[82, 33],
       [82, 26],
       [ 1, 21],
       [41, 52],
       [19, 25],
       [61, 58],
       [85,  2],
       [ 1, 52],
       [89, 59],
       [55, 26]])

In [45]:
# calling specific rows array[[row1,row2]]
a[[0,-1]]

array([[82, 43,  3,  6, 43, 55, 31, 24,  2, 33],
       [55, 69, 61, 32, 93, 36, 27, 73, 70, 26]])

In [46]:
a[:,[0,-1]]=0
a[[0,-1]]=0
a

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 10, 81, 44,  5, 18, 63, 31, 60,  0],
       [ 0, 98, 16, 42,  8, 53, 49,  1, 37,  0],
       [ 0, 65, 96, 93,  7, 13, 22, 75, 63,  0],
       [ 0,  7, 62, 34, 63, 43, 51, 52, 52,  0],
       [ 0, 73, 90, 78, 72, 83, 23, 59, 43,  0],
       [ 0, 51, 86, 74, 39, 59, 63, 29, 25,  0],
       [ 0, 20, 97, 66, 44, 56, 64, 36, 83,  0],
       [ 0, 99, 87, 90, 15, 89, 26, 83, 56,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [48]:
# try the exercise using the np.padding method.
a=np.random.randint(1,100, size=(10,10))
a

array([[30, 20, 57, 44, 95, 60, 67,  1, 32, 27],
       [36, 67, 38, 99, 67, 22, 12, 30, 85, 49],
       [71, 29, 88, 53, 52,  3, 47, 92, 94, 53],
       [65, 44, 10, 87,  4, 88, 20, 91,  7, 11],
       [98,  4, 65, 33, 34,  9, 80, 54, 99, 23],
       [19, 99, 80, 46, 18, 84, 53, 75, 87, 99],
       [57, 40, 66, 26, 50, 22, 98, 96, 73, 55],
       [63, 11, 24, 25, 64, 73, 49, 28,  5, 65],
       [44,  1, 53, 84, 96, 74, 85, 62, 99, 58],
       [12, 41, 42, 89, 12,  8, 63, 20, 93, 30]])

In [49]:
np.pad(a, pad_width=1, mode='constant', constant_values=0)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 30, 20, 57, 44, 95, 60, 67,  1, 32, 27,  0],
       [ 0, 36, 67, 38, 99, 67, 22, 12, 30, 85, 49,  0],
       [ 0, 71, 29, 88, 53, 52,  3, 47, 92, 94, 53,  0],
       [ 0, 65, 44, 10, 87,  4, 88, 20, 91,  7, 11,  0],
       [ 0, 98,  4, 65, 33, 34,  9, 80, 54, 99, 23,  0],
       [ 0, 19, 99, 80, 46, 18, 84, 53, 75, 87, 99,  0],
       [ 0, 57, 40, 66, 26, 50, 22, 98, 96, 73, 55,  0],
       [ 0, 63, 11, 24, 25, 64, 73, 49, 28,  5, 65,  0],
       [ 0, 44,  1, 53, 84, 96, 74, 85, 62, 99, 58,  0],
       [ 0, 12, 41, 42, 89, 12,  8, 63, 20, 93, 30,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [51]:
Nan
Nan
Nan
Nan
Nan
True

NameError: name 'Nan' is not defined

In [50]:
0 * np.nan

nan

In [52]:
np.nan == np.nan

False

In [53]:
np.inf > np.nan

False

In [54]:
np.nan - np.nan

nan

In [55]:
np.nan in set([np.nan])

True

In [56]:
0.3 == 3 * 0.1

False

In [57]:
3*0.1

0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [77]:
a = np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [78]:
np.diag(a, k=-1)

array([0., 0., 0., 0.])

In [79]:
i.hint(18)

hint: np.diag


In [80]:
# after reading the doc string again try another example.
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [84]:
np.diag(x)

array([0, 4, 8])

In [86]:
type(np.diag(x))

numpy.ndarray

In [87]:
#example from doc string
np.diag(np.diag(x), k=-1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0]])

In [82]:
np.diag(np.array([1,2,3,4]),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)