# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
import initialise as i

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
i.hint(2)

hint: np.__version__, np.show_config)


In [4]:
np.__version__

'1.17.4'

In [5]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
a = np.zeros(10, dtype=int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
i.hint(4)

hint: size, itemsize


In [8]:
f'size: This attribute gives the number of elements present in the NumPy array: {a.size}, itemsize: This attribute gives the memory size of one element of NumPy array in bytes: {a.itemsize}'

'size: This attribute gives the number of elements present in the NumPy array: 10, itemsize: This attribute gives the memory size of one element of NumPy array in bytes: 8'

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [9]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x7f87e20f68d0>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [11]:
i.hint(6)

hint: array[4]


Checked solution, and got the same answer

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [13]:
i.hint(8)

hint: array[::-1]


In [14]:
b[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
i.hint(9)

hint: reshape


In [16]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [17]:
c=np.array([1,2,0,0,4,0])
c=c[c!=0]


In [18]:
np.indices((0,3))

array([], shape=(2, 0, 3), dtype=int64)

In [19]:
print(np.indices((0,3)))

[]


In [20]:
np.indices((1,3)).shape

(2, 1, 3)

In [21]:
i.hint(10)

hint: np.nonzero


In [22]:
c=np.array([1,2,0,0,4,0])
c

array([1, 2, 0, 0, 4, 0])

In [23]:
d =np.nonzero(c)
d, type(d)

((array([0, 1, 4]),), tuple)

In [24]:
d[0]

array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [25]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [26]:
np.random.randn(3,3,3)

array([[[-0.24277058, -2.44649283,  0.63301514],
        [-0.29248274,  1.34025077,  0.72642967],
        [-0.96440784, -0.08890657,  0.2837743 ]],

       [[ 2.06040922, -0.64494576,  0.90416401],
        [-0.25260263, -0.0494907 , -1.50558564],
        [ 1.98468411, -1.11849415, -1.53433802]],

       [[ 0.05789235, -0.83611568,  0.84847567],
        [ 3.1507272 ,  0.69352381,  0.62586138],
        [ 0.68585419, -0.91375548, -0.50941985]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [27]:
a = np.random.randn(10, 10)

In [28]:
a.min()

-2.6001997518533364

In [29]:
a.max()

2.4734280499251136

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [30]:
a=np.random.randn(30)
a

array([-0.36784876, -1.15580415,  0.17315116, -0.60234868, -0.268638  ,
        0.65334903, -0.15010764,  0.2457588 ,  1.47452219, -0.30280575,
       -0.38536098,  0.47211417, -0.92974014, -1.42821767,  2.05159014,
       -0.43222274,  0.21136422, -2.16025475, -0.56202795,  0.09273103,
        1.15264476, -1.94492326, -1.02288185,  0.66425935,  0.20929542,
       -1.35994968, -0.98999846,  1.78484516, -1.00067709,  1.74077484])

In [31]:
a.mean()

-0.1379135756015045

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [32]:
i.hint(15)

hint: array[1:-1, 1:-1]


In [33]:
a = np.ones((10,10))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [34]:
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [35]:
a[1:-1,1:-1]

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [37]:
a = np.random.randint(1,100,size=(10,10))
a

array([[20, 44,  2, 85, 43,  7, 57, 64, 20, 65],
       [32,  6, 48, 73,  8, 46, 30, 38, 26, 50],
       [12, 66, 54, 41, 52, 73, 16, 25, 80, 10],
       [74, 36, 90, 47, 64, 44,  5,  3, 63, 31],
       [34, 81, 65, 69, 76, 51, 53, 71, 28, 77],
       [64, 80, 73,  2, 45, 80, 34, 94, 13, 28],
       [80, 13,  8, 96,  4, 85, 55, 10, 54, 56],
       [83, 63, 96, 33, 26,  6, 89, 36, 53, 57],
       [48, 42, 37, 33, 16, 51, 42, 54, 63, 73],
       [ 3, 30, 56, 30, 31, 81, 17, 83, 73, 31]])

In [38]:
a[:,0]=0
a

array([[ 0, 44,  2, 85, 43,  7, 57, 64, 20, 65],
       [ 0,  6, 48, 73,  8, 46, 30, 38, 26, 50],
       [ 0, 66, 54, 41, 52, 73, 16, 25, 80, 10],
       [ 0, 36, 90, 47, 64, 44,  5,  3, 63, 31],
       [ 0, 81, 65, 69, 76, 51, 53, 71, 28, 77],
       [ 0, 80, 73,  2, 45, 80, 34, 94, 13, 28],
       [ 0, 13,  8, 96,  4, 85, 55, 10, 54, 56],
       [ 0, 63, 96, 33, 26,  6, 89, 36, 53, 57],
       [ 0, 42, 37, 33, 16, 51, 42, 54, 63, 73],
       [ 0, 30, 56, 30, 31, 81, 17, 83, 73, 31]])

In [39]:
a[:,-1]=0
a

array([[ 0, 44,  2, 85, 43,  7, 57, 64, 20,  0],
       [ 0,  6, 48, 73,  8, 46, 30, 38, 26,  0],
       [ 0, 66, 54, 41, 52, 73, 16, 25, 80,  0],
       [ 0, 36, 90, 47, 64, 44,  5,  3, 63,  0],
       [ 0, 81, 65, 69, 76, 51, 53, 71, 28,  0],
       [ 0, 80, 73,  2, 45, 80, 34, 94, 13,  0],
       [ 0, 13,  8, 96,  4, 85, 55, 10, 54,  0],
       [ 0, 63, 96, 33, 26,  6, 89, 36, 53,  0],
       [ 0, 42, 37, 33, 16, 51, 42, 54, 63,  0],
       [ 0, 30, 56, 30, 31, 81, 17, 83, 73,  0]])

In [40]:
a[0]=0
a

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  6, 48, 73,  8, 46, 30, 38, 26,  0],
       [ 0, 66, 54, 41, 52, 73, 16, 25, 80,  0],
       [ 0, 36, 90, 47, 64, 44,  5,  3, 63,  0],
       [ 0, 81, 65, 69, 76, 51, 53, 71, 28,  0],
       [ 0, 80, 73,  2, 45, 80, 34, 94, 13,  0],
       [ 0, 13,  8, 96,  4, 85, 55, 10, 54,  0],
       [ 0, 63, 96, 33, 26,  6, 89, 36, 53,  0],
       [ 0, 42, 37, 33, 16, 51, 42, 54, 63,  0],
       [ 0, 30, 56, 30, 31, 81, 17, 83, 73,  0]])

In [41]:
a[-1]=0
a

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  6, 48, 73,  8, 46, 30, 38, 26,  0],
       [ 0, 66, 54, 41, 52, 73, 16, 25, 80,  0],
       [ 0, 36, 90, 47, 64, 44,  5,  3, 63,  0],
       [ 0, 81, 65, 69, 76, 51, 53, 71, 28,  0],
       [ 0, 80, 73,  2, 45, 80, 34, 94, 13,  0],
       [ 0, 13,  8, 96,  4, 85, 55, 10, 54,  0],
       [ 0, 63, 96, 33, 26,  6, 89, 36, 53,  0],
       [ 0, 42, 37, 33, 16, 51, 42, 54, 63,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [42]:
a=np.random.randint(1,100, size=(10,10))
a

array([[54,  1, 44, 73, 48,  6, 33, 22, 72, 30],
       [45, 47, 69, 96, 73, 25, 38, 51,  2, 79],
       [61, 50, 87, 86, 91, 23, 28, 64, 92, 10],
       [28, 55, 47, 48,  7, 84, 93, 50, 88, 74],
       [55, 72, 31,  8, 81, 32, 82, 17, 83, 52],
       [53, 92, 58, 53, 80, 77, 82, 51, 62, 62],
       [17, 52, 89, 31, 68, 89, 22, 61, 73, 63],
       [97,  7,  4, 30, 39, 35, 66, 56, 84, 73],
       [20, 55, 50, 36, 16, 31, 51, 37, 86, 80],
       [14, 93, 97, 24, 24, 86, 43, 47, 90, 26]])

In [43]:
#calling specific columns array[:,[column1,column2]]
a[:,[0,-1]]

array([[54, 30],
       [45, 79],
       [61, 10],
       [28, 74],
       [55, 52],
       [53, 62],
       [17, 63],
       [97, 73],
       [20, 80],
       [14, 26]])

In [44]:
# calling specific rows array[[row1,row2]]
a[[0,-1]]

array([[54,  1, 44, 73, 48,  6, 33, 22, 72, 30],
       [14, 93, 97, 24, 24, 86, 43, 47, 90, 26]])

In [45]:
a[:,[0,-1]]=0
a[[0,-1]]=0
a

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 47, 69, 96, 73, 25, 38, 51,  2,  0],
       [ 0, 50, 87, 86, 91, 23, 28, 64, 92,  0],
       [ 0, 55, 47, 48,  7, 84, 93, 50, 88,  0],
       [ 0, 72, 31,  8, 81, 32, 82, 17, 83,  0],
       [ 0, 92, 58, 53, 80, 77, 82, 51, 62,  0],
       [ 0, 52, 89, 31, 68, 89, 22, 61, 73,  0],
       [ 0,  7,  4, 30, 39, 35, 66, 56, 84,  0],
       [ 0, 55, 50, 36, 16, 31, 51, 37, 86,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [46]:
# try the exercise using the np.padding method.
a=np.random.randint(1,100, size=(10,10))
a

array([[37, 86, 32, 83, 25, 53, 40, 70, 20, 45],
       [94, 78, 54, 80, 70, 70, 84, 72, 71, 23],
       [16, 94, 20, 81, 85, 16,  8, 47, 12, 20],
       [73, 91, 96, 15, 99, 87, 38, 21, 55,  3],
       [55, 85, 45, 77, 85, 51, 55, 50, 55, 72],
       [92, 50, 52, 67, 72,  1, 40, 83, 71, 15],
       [57, 77, 54, 40, 16, 36, 68, 88, 29, 91],
       [22, 28, 69, 24, 30, 62, 85, 76, 25, 96],
       [94, 11, 94, 85,  9, 99, 46, 29, 14, 31],
       [56, 64, 60, 80, 79, 84, 60, 58, 89, 42]])

In [47]:
np.pad(a, pad_width=1, mode='constant', constant_values=0)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 37, 86, 32, 83, 25, 53, 40, 70, 20, 45,  0],
       [ 0, 94, 78, 54, 80, 70, 70, 84, 72, 71, 23,  0],
       [ 0, 16, 94, 20, 81, 85, 16,  8, 47, 12, 20,  0],
       [ 0, 73, 91, 96, 15, 99, 87, 38, 21, 55,  3,  0],
       [ 0, 55, 85, 45, 77, 85, 51, 55, 50, 55, 72,  0],
       [ 0, 92, 50, 52, 67, 72,  1, 40, 83, 71, 15,  0],
       [ 0, 57, 77, 54, 40, 16, 36, 68, 88, 29, 91,  0],
       [ 0, 22, 28, 69, 24, 30, 62, 85, 76, 25, 96,  0],
       [ 0, 94, 11, 94, 85,  9, 99, 46, 29, 14, 31,  0],
       [ 0, 56, 64, 60, 80, 79, 84, 60, 58, 89, 42,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [48]:
# Nan
# Nan
# Nan
# Nan
# Nan
# True

In [49]:
0 * np.nan

nan

In [50]:
np.nan == np.nan

False

In [51]:
np.inf > np.nan

False

In [52]:
np.nan - np.nan

nan

In [53]:
np.nan in set([np.nan])

True

In [54]:
0.3 == 3 * 0.1

False

In [55]:
3*0.1

0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [56]:
a = np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [57]:
np.diag(a, k=-1)

array([0., 0., 0., 0.])

In [58]:
i.hint(18)

hint: np.diag


In [59]:
# after reading the doc string again try another example.
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
np.diag(x)

array([0, 4, 8])

In [61]:
type(np.diag(x))

numpy.ndarray

In [62]:
#example from doc string
np.diag(np.diag(x), k=-1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0]])

In [63]:
np.diag(np.array([1,2,3,4]),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [64]:
eight_eight = np.ones((8,8))
eight_eight


array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [65]:
a = np.diag(np.array([1,1]), k=-3)
a
            

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]])

In [66]:
np.diag(a , k=-1)

array([0, 0, 0, 0])

In [67]:
i.hint(19)

hint: array[::2]


In [68]:
a = np.arange(1,65).reshape((8,8))
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [69]:
a[::2]

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [49, 50, 51, 52, 53, 54, 55, 56]])

In [70]:
a[::2,::2] = 0

In [71]:
a

array([[ 0,  2,  0,  4,  0,  6,  0,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [ 0, 18,  0, 20,  0, 22,  0, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [ 0, 34,  0, 36,  0, 38,  0, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [ 0, 50,  0, 52,  0, 54,  0, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [72]:
a[::-2,::-2]=0
a

array([[ 0,  2,  0,  4,  0,  6,  0,  8],
       [ 9,  0, 11,  0, 13,  0, 15,  0],
       [ 0, 18,  0, 20,  0, 22,  0, 24],
       [25,  0, 27,  0, 29,  0, 31,  0],
       [ 0, 34,  0, 36,  0, 38,  0, 40],
       [41,  0, 43,  0, 45,  0, 47,  0],
       [ 0, 50,  0, 52,  0, 54,  0, 56],
       [57,  0, 59,  0, 61,  0, 63,  0]])

In [73]:
a = np.ones((8,8),dtype=int)
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [74]:
a[::2,::2]=0
a[::-2,::-2]=0
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [75]:
a = np.arange(0,336).reshape(6,7,8)
a

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [76]:
x, y, z = np.indices((6,7,8), sparse=True)

In [77]:
x

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [78]:
y

array([[[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6]]])

In [79]:
z

array([[[0, 1, 2, 3, 4, 5, 6, 7]]])

In [80]:
a[1,5,3]

99

In [81]:
i.hint(20)

hint: np.unravel_index


In [82]:
np.unravel_index([99],shape=(6,7,8))

(array([1]), array([5]), array([3]))

In [83]:
# practice navigating in the object
x , y, z = np.unravel_index([99], shape=(6,7,8))
x[0], y[0], z[0]

(1, 5, 3)

In [84]:
v = np.unravel_index([99], shape=(6,7,8))
v

(array([1]), array([5]), array([3]))

In [85]:
v[0][0], v[1][0], v[2][0]

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [86]:
a=np.array(([0,1],[1,0]))
a

array([[0, 1],
       [1, 0]])

In [87]:
np.tile(a,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [88]:
a=np.random.randint(1,100, size=(5,5))
a

array([[77, 74, 31, 80, 83],
       [ 8, 96, 33, 66, 75],
       [79, 41,  2,  6, 68],
       [82, 69, 37, 20, 13],
       [66, 73, 56, 62, 54]])

In [89]:
from  sklearn.preprocessing import normalize

In [90]:
normed_matrix = normalize(a, axis=1, norm='l1')
normed_matrix

array([[0.22318841, 0.21449275, 0.08985507, 0.23188406, 0.24057971],
       [0.02877698, 0.34532374, 0.11870504, 0.23741007, 0.26978417],
       [0.40306122, 0.20918367, 0.01020408, 0.03061224, 0.34693878],
       [0.37104072, 0.31221719, 0.16742081, 0.09049774, 0.05882353],
       [0.21221865, 0.23472669, 0.18006431, 0.19935691, 0.17363344]])

In [91]:
i.hint(22)

hint: (x -mean)/std


In [92]:
for x in a:
    print(x)

[77 74 31 80 83]
[ 8 96 33 66 75]
[79 41  2  6 68]
[82 69 37 20 13]
[66 73 56 62 54]


In [93]:
a.mean()

54.04

In [94]:
(a - a.mean())/a.std()

array([[ 8.42049662e-01,  7.32025752e-01, -8.44983633e-01,
         9.52073573e-01,  1.06209748e+00],
       [-1.68850028e+00,  1.53886776e+00, -7.71634359e-01,
         4.38628657e-01,  7.68700388e-01],
       [ 9.15398936e-01, -4.78237265e-01, -1.90854810e+00,
        -1.76184955e+00,  5.11977930e-01],
       [ 1.02542285e+00,  5.48652567e-01, -6.24935812e-01,
        -1.24840464e+00, -1.50512710e+00],
       [ 4.38628657e-01,  6.95351115e-01,  7.18822882e-02,
         2.91930109e-01, -1.46698547e-03]])

In [95]:
(a - np.mean(a))/np.std(a)

array([[ 8.42049662e-01,  7.32025752e-01, -8.44983633e-01,
         9.52073573e-01,  1.06209748e+00],
       [-1.68850028e+00,  1.53886776e+00, -7.71634359e-01,
         4.38628657e-01,  7.68700388e-01],
       [ 9.15398936e-01, -4.78237265e-01, -1.90854810e+00,
        -1.76184955e+00,  5.11977930e-01],
       [ 1.02542285e+00,  5.48652567e-01, -6.24935812e-01,
        -1.24840464e+00, -1.50512710e+00],
       [ 4.38628657e-01,  6.95351115e-01,  7.18822882e-02,
         2.91930109e-01, -1.46698547e-03]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [96]:
np.dtype(np.int16)


dtype('int16')

In [97]:
color = np.dtype({'names':['R','G','B','A'], 'formats':[np.ubyte, np.ubyte, np.ubyte, np.ubyte]})

In [98]:
color

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

In [99]:
color('R')

TypeError: 'numpy.dtype' object is not callable

In [100]:
# Python program to demonstrate 
# the use of data type object with structured array. 
import numpy as np 

dt = np.dtype([('name', np.unicode_, 16), ('grades', np.float64, (2,))]) 

# x is a structured array with names and marks of students. 
# Data type of name of the student is np.unicode_ and 
# data type of marks is np.float(64) 
x = np.array([('Sarah', (8.0, 7.0)), ('John', (6.0, 7.0))], dtype=dt) 

print(x[1]) 
print("Grades of John are: ",x[1]['grades']) 
print("Names are: ",x['name']) 


('John', [6., 7.])
Grades of John are:  [6. 7.]
Names are:  ['Sarah' 'John']


In [101]:
# Try it without assigning a data type.
x = np.array([('Sarah', (8.0, 7.0)), ('John', (6.0, 7.0))])
x

array([['Sarah', (8.0, 7.0)],
       ['John', (6.0, 7.0)]], dtype=object)

In [102]:
x[1]['grades']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [103]:
# Let's go back to colors.
RGBA = np.dtype({'names':['R','G','B','A'], 'formats':[np.ubyte, np.ubyte, np.ubyte, np.ubyte]})

In [104]:
colors = np.array([1,2,3,4], dtype=RGBA)
colors

array([(1, 1, 1, 1), (2, 2, 2, 2), (3, 3, 3, 3), (4, 4, 4, 4)],
      dtype=[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

In [105]:
colors['R']

array([1, 2, 3, 4], dtype=uint8)

In [106]:
# try with a tuple

In [107]:
RGBA = np.dtype([('r', np.ubyte)])
colors = np.array((1), dtype=RGBA)
colors

array((1,), dtype=[('r', 'u1')])

In [108]:
np.array(colors['r'])

array(1, dtype=uint8)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [113]:
a = np.random.randint(1,100, size=(5,3))
a

array([[33,  5, 61],
       [94, 12, 59],
       [40, 81, 21],
       [13,  9, 45],
       [78, 87, 30]])

In [114]:
b = np.random.randint(1,100, size=(3,2))
b

array([[87, 66],
       [47, 73],
       [76, 19]])

In [122]:
np.dot(a,b)

array([[ 7742,  3702],
       [13226,  8201],
       [ 8883,  8952],
       [ 4974,  2370],
       [13155, 12069]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [158]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [159]:
np.array([ -x if 8>=x>=3 else x for x in np.arange(11)])

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

In [151]:
# the solution method uses masking
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [152]:
# we can create an array that is the mask of greater than 3 and less than 8
greater_than_3 = 3 < a
less_than_8 = a < 8
greater_than_3, less_than_8

(array([False, False, False, False,  True,  True,  True,  True,  True,
         True,  True]),
 array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        False, False]))

In [153]:
# we can also create a mask that combines these
mask = (greater_than_3) & (less_than_8)
mask

array([False, False, False, False,  True,  True,  True,  True, False,
       False, False])

In [154]:
# now returning the array in place
a[mask]

array([4, 5, 6, 7])

In [161]:
# a[mask] only returns where the values are true. If the values are true we want to multiply them by -1
a[mask] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)