# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
import initialise as i

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
i.hint(2)

hint: np.__version__, np.show_config)


In [4]:
np.__version__

'1.17.4'

In [5]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/anaconda3/include']


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
a = np.zeros(10, dtype=int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
i.hint(4)

hint: size, itemsize


In [8]:
f'size: This attribute gives the number of elements present in the NumPy array: {a.size}, itemsize: This attribute gives the memory size of one element of NumPy array in bytes: {a.itemsize}'

'size: This attribute gives the number of elements present in the NumPy array: 10, itemsize: This attribute gives the memory size of one element of NumPy array in bytes: 8'

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [9]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x7fe2a17f69e8>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [11]:
i.hint(6)

hint: array[4]


Checked solution, and got the same answer

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [13]:
i.hint(8)

hint: array[::-1]


In [14]:
b[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
i.hint(9)

hint: reshape


In [16]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [17]:
c=np.array([1,2,0,0,4,0])
c=c[c!=0]


In [18]:
np.indices((0,3))

array([], shape=(2, 0, 3), dtype=int64)

In [19]:
print(np.indices((0,3)))

[]


In [20]:
np.indices((1,3)).shape

(2, 1, 3)

In [21]:
i.hint(10)

hint: np.nonzero


In [22]:
c=np.array([1,2,0,0,4,0])
c

array([1, 2, 0, 0, 4, 0])

In [23]:
d =np.nonzero(c)
d, type(d)

((array([0, 1, 4]),), tuple)

In [24]:
d[0]

array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [25]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [26]:
np.random.randn(3,3,3)

array([[[ 0.1632262 ,  0.06693856, -0.58957669],
        [ 0.47750639, -1.59543912, -1.41272646],
        [-1.47230876,  0.06537745, -0.66456172]],

       [[ 1.35382727,  0.49274776, -2.02920065],
        [-1.05956222,  0.43806336,  2.22162747],
        [ 1.03356948,  0.94732746, -0.32901427]],

       [[ 0.80646137, -1.18474809, -1.94374705],
        [ 0.39155963, -1.83754622, -2.53231891],
        [-0.52623006,  1.28121744,  4.14686973]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [27]:
a = np.random.randn(10, 10)

In [28]:
a.min()

-1.6407420267755297

In [29]:
a.max()

3.052317224777022

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [30]:
a=np.random.randn(30)
a

array([ 0.78853814,  0.33836944, -0.59503535, -0.29660025,  0.28082748,
       -0.18505313,  0.23794251,  1.2242019 ,  0.11756836, -0.16728573,
       -0.14636772,  1.41071492,  0.97255787, -1.40645396, -0.36610452,
       -0.86412864, -1.60955483,  0.56412052,  1.08856635, -0.15644886,
       -0.61194257,  0.02862673, -0.20386131,  0.76765157,  0.50125235,
       -0.52702947,  0.86254938,  1.53780927, -0.93924897, -0.00927046])

In [31]:
a.mean()

0.08789703414335645

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [32]:
i.hint(15)

hint: array[1:-1, 1:-1]


In [33]:
a = np.ones((10,10))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [34]:
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [35]:
a[1:-1,1:-1]

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [37]:
a = np.random.randint(1,100,size=(10,10))
a

array([[62, 61, 33,  6, 82, 50, 70, 84, 35, 17],
       [76, 80, 56, 71, 96, 70, 13, 80, 50, 64],
       [18, 83, 48, 15, 50,  7,  5,  2,  3, 92],
       [47, 70, 63, 46, 87, 70, 36, 65, 80,  4],
       [90, 58, 88, 89, 51, 90, 94, 86, 35, 36],
       [29, 49, 22, 80, 66, 48, 75, 57,  3, 70],
       [89, 91, 18, 57, 75, 64,  6, 60, 41, 10],
       [64, 72, 22, 94, 15,  8, 11, 24, 25, 98],
       [32, 31, 97, 38, 95, 51, 62, 11, 53, 11],
       [15, 72, 73, 47, 38, 29, 10, 85, 71, 88]])

In [38]:
a[:,0]=0
a

array([[ 0, 61, 33,  6, 82, 50, 70, 84, 35, 17],
       [ 0, 80, 56, 71, 96, 70, 13, 80, 50, 64],
       [ 0, 83, 48, 15, 50,  7,  5,  2,  3, 92],
       [ 0, 70, 63, 46, 87, 70, 36, 65, 80,  4],
       [ 0, 58, 88, 89, 51, 90, 94, 86, 35, 36],
       [ 0, 49, 22, 80, 66, 48, 75, 57,  3, 70],
       [ 0, 91, 18, 57, 75, 64,  6, 60, 41, 10],
       [ 0, 72, 22, 94, 15,  8, 11, 24, 25, 98],
       [ 0, 31, 97, 38, 95, 51, 62, 11, 53, 11],
       [ 0, 72, 73, 47, 38, 29, 10, 85, 71, 88]])

In [39]:
a[:,-1]=0
a

array([[ 0, 61, 33,  6, 82, 50, 70, 84, 35,  0],
       [ 0, 80, 56, 71, 96, 70, 13, 80, 50,  0],
       [ 0, 83, 48, 15, 50,  7,  5,  2,  3,  0],
       [ 0, 70, 63, 46, 87, 70, 36, 65, 80,  0],
       [ 0, 58, 88, 89, 51, 90, 94, 86, 35,  0],
       [ 0, 49, 22, 80, 66, 48, 75, 57,  3,  0],
       [ 0, 91, 18, 57, 75, 64,  6, 60, 41,  0],
       [ 0, 72, 22, 94, 15,  8, 11, 24, 25,  0],
       [ 0, 31, 97, 38, 95, 51, 62, 11, 53,  0],
       [ 0, 72, 73, 47, 38, 29, 10, 85, 71,  0]])

In [40]:
a[0]=0
a

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 80, 56, 71, 96, 70, 13, 80, 50,  0],
       [ 0, 83, 48, 15, 50,  7,  5,  2,  3,  0],
       [ 0, 70, 63, 46, 87, 70, 36, 65, 80,  0],
       [ 0, 58, 88, 89, 51, 90, 94, 86, 35,  0],
       [ 0, 49, 22, 80, 66, 48, 75, 57,  3,  0],
       [ 0, 91, 18, 57, 75, 64,  6, 60, 41,  0],
       [ 0, 72, 22, 94, 15,  8, 11, 24, 25,  0],
       [ 0, 31, 97, 38, 95, 51, 62, 11, 53,  0],
       [ 0, 72, 73, 47, 38, 29, 10, 85, 71,  0]])

In [41]:
a[-1]=0
a

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 80, 56, 71, 96, 70, 13, 80, 50,  0],
       [ 0, 83, 48, 15, 50,  7,  5,  2,  3,  0],
       [ 0, 70, 63, 46, 87, 70, 36, 65, 80,  0],
       [ 0, 58, 88, 89, 51, 90, 94, 86, 35,  0],
       [ 0, 49, 22, 80, 66, 48, 75, 57,  3,  0],
       [ 0, 91, 18, 57, 75, 64,  6, 60, 41,  0],
       [ 0, 72, 22, 94, 15,  8, 11, 24, 25,  0],
       [ 0, 31, 97, 38, 95, 51, 62, 11, 53,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [42]:
a=np.random.randint(1,100, size=(10,10))
a

array([[21, 64, 72, 44, 83, 44, 29, 60, 66, 15],
       [67, 92, 21, 11, 30, 63, 79, 49, 38, 46],
       [53, 93, 13, 29, 22, 77, 55,  6, 91, 72],
       [98, 77, 22, 58, 70, 90, 11, 79, 11, 47],
       [99, 30, 71, 17, 32, 85, 64, 74, 91,  9],
       [57,  2, 83, 20, 35, 15, 48, 46,  8, 68],
       [71, 56, 19, 70, 89, 95, 12, 13, 62,  7],
       [35, 82, 36, 48, 58, 37, 52, 91, 94, 13],
       [34, 84, 28, 85, 48, 25, 40, 40, 49, 52],
       [80, 22, 67,  8, 29, 96, 19, 26, 21, 13]])

In [43]:
#calling specific columns array[:,[column1,column2]]
a[:,[0,-1]]

array([[21, 15],
       [67, 46],
       [53, 72],
       [98, 47],
       [99,  9],
       [57, 68],
       [71,  7],
       [35, 13],
       [34, 52],
       [80, 13]])

In [44]:
# calling specific rows array[[row1,row2]]
a[[0,-1]]

array([[21, 64, 72, 44, 83, 44, 29, 60, 66, 15],
       [80, 22, 67,  8, 29, 96, 19, 26, 21, 13]])

In [45]:
a[:,[0,-1]]=0
a[[0,-1]]=0
a

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 92, 21, 11, 30, 63, 79, 49, 38,  0],
       [ 0, 93, 13, 29, 22, 77, 55,  6, 91,  0],
       [ 0, 77, 22, 58, 70, 90, 11, 79, 11,  0],
       [ 0, 30, 71, 17, 32, 85, 64, 74, 91,  0],
       [ 0,  2, 83, 20, 35, 15, 48, 46,  8,  0],
       [ 0, 56, 19, 70, 89, 95, 12, 13, 62,  0],
       [ 0, 82, 36, 48, 58, 37, 52, 91, 94,  0],
       [ 0, 84, 28, 85, 48, 25, 40, 40, 49,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [46]:
# try the exercise using the np.padding method.
a=np.random.randint(1,100, size=(10,10))
a

array([[39, 45, 61, 53, 51, 54,  3, 18, 42, 35],
       [11,  6, 90, 27, 37, 21, 99, 60, 16, 96],
       [90,  6, 89, 94,  7, 13, 80, 98, 30, 30],
       [19,  3, 17, 47, 77, 44, 61, 62, 49, 13],
       [10, 65, 74, 60, 20, 95, 91, 33, 21, 66],
       [20, 40, 23, 97,  2, 19, 11, 19, 60, 53],
       [74, 76, 23, 18, 80, 32, 53, 27, 27, 40],
       [49, 63, 45, 34, 32, 14, 42, 78, 78, 52],
       [54,  1, 35, 68,  4, 37, 88, 66, 63, 17],
       [49, 29,  2, 48, 52, 10, 89, 38, 36, 26]])

In [47]:
np.pad(a, pad_width=1, mode='constant', constant_values=0)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 39, 45, 61, 53, 51, 54,  3, 18, 42, 35,  0],
       [ 0, 11,  6, 90, 27, 37, 21, 99, 60, 16, 96,  0],
       [ 0, 90,  6, 89, 94,  7, 13, 80, 98, 30, 30,  0],
       [ 0, 19,  3, 17, 47, 77, 44, 61, 62, 49, 13,  0],
       [ 0, 10, 65, 74, 60, 20, 95, 91, 33, 21, 66,  0],
       [ 0, 20, 40, 23, 97,  2, 19, 11, 19, 60, 53,  0],
       [ 0, 74, 76, 23, 18, 80, 32, 53, 27, 27, 40,  0],
       [ 0, 49, 63, 45, 34, 32, 14, 42, 78, 78, 52,  0],
       [ 0, 54,  1, 35, 68,  4, 37, 88, 66, 63, 17,  0],
       [ 0, 49, 29,  2, 48, 52, 10, 89, 38, 36, 26,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [48]:
# Nan
# Nan
# Nan
# Nan
# Nan
# True

In [49]:
0 * np.nan

nan

In [50]:
np.nan == np.nan

False

In [51]:
np.inf > np.nan

False

In [52]:
np.nan - np.nan

nan

In [53]:
np.nan in set([np.nan])

True

In [54]:
0.3 == 3 * 0.1

False

In [55]:
3*0.1

0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [56]:
a = np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [57]:
np.diag(a, k=-1)

array([0., 0., 0., 0.])

In [58]:
i.hint(18)

hint: np.diag


In [59]:
# after reading the doc string again try another example.
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
np.diag(x)

array([0, 4, 8])

In [61]:
type(np.diag(x))

numpy.ndarray

In [62]:
#example from doc string
np.diag(np.diag(x), k=-1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0]])

In [63]:
np.diag(np.array([1,2,3,4]),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [64]:
eight_eight = np.ones((8,8))
eight_eight


array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [65]:
a = np.diag(np.array([1,1]), k=-3)
a
            

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]])

In [66]:
np.diag(a , k=-1)

array([0, 0, 0, 0])

In [67]:
i.hint(19)

hint: array[::2]


In [68]:
a = np.arange(1,65).reshape((8,8))
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [69]:
a[::2]

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [49, 50, 51, 52, 53, 54, 55, 56]])

In [70]:
a[::2,::2] = 0

In [71]:
a

array([[ 0,  2,  0,  4,  0,  6,  0,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [ 0, 18,  0, 20,  0, 22,  0, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [ 0, 34,  0, 36,  0, 38,  0, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [ 0, 50,  0, 52,  0, 54,  0, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [72]:
a[::-2,::-2]=0
a

array([[ 0,  2,  0,  4,  0,  6,  0,  8],
       [ 9,  0, 11,  0, 13,  0, 15,  0],
       [ 0, 18,  0, 20,  0, 22,  0, 24],
       [25,  0, 27,  0, 29,  0, 31,  0],
       [ 0, 34,  0, 36,  0, 38,  0, 40],
       [41,  0, 43,  0, 45,  0, 47,  0],
       [ 0, 50,  0, 52,  0, 54,  0, 56],
       [57,  0, 59,  0, 61,  0, 63,  0]])

In [73]:
a = np.ones((8,8),dtype=int)
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [74]:
a[::2,::2]=0
a[::-2,::-2]=0
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [75]:
a = np.arange(0,336).reshape(6,7,8)
a

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [76]:
x, y, z = np.indices((6,7,8), sparse=True)

In [77]:
x

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [78]:
y

array([[[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6]]])

In [79]:
z

array([[[0, 1, 2, 3, 4, 5, 6, 7]]])

In [80]:
a[1,5,3]

99

In [81]:
i.hint(20)

hint: np.unravel_index


In [82]:
np.unravel_index([99],shape=(6,7,8))

(array([1]), array([5]), array([3]))

In [83]:
# practice navigating in the object
x , y, z = np.unravel_index([99], shape=(6,7,8))
x[0], y[0], z[0]

(1, 5, 3)

In [84]:
v = np.unravel_index([99], shape=(6,7,8))
v

(array([1]), array([5]), array([3]))

In [85]:
v[0][0], v[1][0], v[2][0]

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [86]:
a=np.array(([0,1],[1,0]))
a

array([[0, 1],
       [1, 0]])

In [87]:
np.tile(a,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [88]:
a=np.random.randint(1,100, size=(5,5))
a

array([[76, 30, 50, 25, 83],
       [53, 17, 67, 48, 76],
       [18, 15, 30, 94, 20],
       [20, 95, 18, 24, 32],
       [47, 10, 67, 84, 28]])

In [89]:
from  sklearn.preprocessing import normalize

In [90]:
normed_matrix = normalize(a, axis=1, norm='l1')
normed_matrix

array([[0.28787879, 0.11363636, 0.18939394, 0.09469697, 0.31439394],
       [0.20306513, 0.0651341 , 0.25670498, 0.18390805, 0.29118774],
       [0.10169492, 0.08474576, 0.16949153, 0.53107345, 0.11299435],
       [0.10582011, 0.5026455 , 0.0952381 , 0.12698413, 0.16931217],
       [0.19915254, 0.04237288, 0.28389831, 0.3559322 , 0.11864407]])

In [91]:
i.hint(22)

hint: (x -mean)/std


In [92]:
for x in a:
    print(x)

[76 30 50 25 83]
[53 17 67 48 76]
[18 15 30 94 20]
[20 95 18 24 32]
[47 10 67 84 28]


In [93]:
a.mean()

45.08

In [94]:
(a - a.mean())/a.std()

array([[ 1.14522163, -0.55853629,  0.18222802, -0.74372737,  1.40448914],
       [ 0.29334267, -1.0400331 ,  0.81187769,  0.10815159,  1.14522163],
       [-1.00299488, -1.11410953, -0.55853629,  1.81190952, -0.92891845],
       [-0.92891845,  1.84894773, -1.00299488, -0.78076559, -0.48445986],
       [ 0.07111337, -1.29930061,  0.81187769,  1.44152736, -0.63261273]])

In [95]:
(a - np.mean(a))/np.std(a)

array([[ 1.14522163, -0.55853629,  0.18222802, -0.74372737,  1.40448914],
       [ 0.29334267, -1.0400331 ,  0.81187769,  0.10815159,  1.14522163],
       [-1.00299488, -1.11410953, -0.55853629,  1.81190952, -0.92891845],
       [-0.92891845,  1.84894773, -1.00299488, -0.78076559, -0.48445986],
       [ 0.07111337, -1.29930061,  0.81187769,  1.44152736, -0.63261273]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [97]:
np.dtype(np.int16)


dtype('int16')

In [115]:
color = np.dtype({'names':['R','G','B','A'], 'formats':[np.ubyte, np.ubyte, np.ubyte, np.ubyte]})

In [116]:
color

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

In [120]:
color('R')

TypeError: 'numpy.dtype' object is not callable

In [121]:
# Python program to demonstrate 
# the use of data type object with structured array. 
import numpy as np 

dt = np.dtype([('name', np.unicode_, 16), ('grades', np.float64, (2,))]) 

# x is a structured array with names and marks of students. 
# Data type of name of the student is np.unicode_ and 
# data type of marks is np.float(64) 
x = np.array([('Sarah', (8.0, 7.0)), ('John', (6.0, 7.0))], dtype=dt) 

print(x[1]) 
print("Grades of John are: ",x[1]['grades']) 
print("Names are: ",x['name']) 


('John', [6., 7.])
Grades of John are:  [6. 7.]
Names are:  ['Sarah' 'John']


In [124]:
# Try it without assigning a data type.
x = np.array([('Sarah', (8.0, 7.0)), ('John', (6.0, 7.0))])
x

array([['Sarah', (8.0, 7.0)],
       ['John', (6.0, 7.0)]], dtype=object)

In [125]:
x[1]['grades']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [128]:
# Let's go back to colors.
RGBA = np.dtype({'names':['R','G','B','A'], 'formats':[np.ubyte, np.ubyte, np.ubyte, np.ubyte]})

In [158]:
colors = np.array([1,2,3,4], dtype=RGBA)
colors

array([(1, 1, 1, 1), (2, 2, 2, 2), (3, 3, 3, 3), (4, 4, 4, 4)],
      dtype=[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

In [157]:
colors['R']

array(1, dtype=uint8)

In [ ]:
# try with a tuple

In [179]:
RGBA = np.dtype([('r', np.ubyte)])
colors = np.array((1), dtype=RGBA)
colors

array((1,), dtype=[('r', 'u1')])

In [186]:
np.array(colors['r'])

array(1, dtype=uint8)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)